server {
        server_name ${{ secrets.OLD_NGINX_SERVER_NAME }};
        location / {
                proxy_pass http://localhost:5678;
                proxy_http_version 1.1;
                proxy_set_header Connection 'Upgrade';
                proxy_set_header Upgrade $http_upgrade;
        }
        location /budibase/ {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $http_host;
                proxy_pass http://localhost:10000;
                #proxy_redirect / /budibase/;
        }

    listen 443 ssl; # managed by either Certbot OR k8s' cert-manager
    ssl_certificate /etc/letsencrypt/live/${{ secrets.OLD_NGINX_SERVER_NAME }}/fullchain.pem; # managed by either Certbot OR k8s' cert-manager
    ssl_certificate_key /etc/letsencrypt/live/${{ secrets.OLD_NGINX_SERVER_NAME }}/privkey.pem; # managed by either Certbot OR k8s' cert-manager
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by either Certbot OR k8s' cert-manager
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by either Certbot OR k8s' cert-manager

}
server {
    if ($host = ${{ secrets.OLD_NGINX_SERVER_NAME }}) {
        return 301 https://$host$request_uri;
    } # managed by either Certbot OR k8s' cert-manager


        server_name ${{ secrets.OLD_NGINX_SERVER_NAME }};

        listen 80;
    return 404; # managed by either Certbot OR k8s' cert-manager


}
