---
apiVersion: v1
kind: Secret
metadata:
    name: ilum-git-credentials
    namespace: ilum
stringData:
    username: "REP_GITEA_CRED_USERNAME"
    password: "REP_GITEA_CRED_USERNAME"
    postgres-password: "REP_GITEA_CRED_POSTGRES_PASSWORD"
type: Opaque

