---
apiVersion: v1
kind: Secret
metadata:
    name: ilum-git-credentials
    namespace: ilum
stringData:
    username: "admin-1"
    password: "1232141"
    postgres-password: "adsadsadas"
type: Opaque

