---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ui-ingress
  namespace: n8n-msg
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - n8n-2.acmeorg.io
    secretName: n8n-core-tls
  rules:
  - host: n8n-2.acmeorg.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              number: 80
