apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-volume
  namespace: airflow
spec:
  storageClassName: openebs-hostpath-node2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

