   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: qdrant-ingress
     namespace: qdrant
     annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /
       cert-manager.io/cluster-issuer: letsencrypt-prod
   spec:
     ingressClassName: nginx
     tls:
       - hosts:
           - ${QDRANT_HOST_0}
         secretName: qdrant-tls
     rules:
       - host: ${QDRANT_HOST_0}
         http:
           paths:
             - path: /
               pathType: Prefix
               backend:
                 service:
                   name: qdrant
                   port:
                     number: 6333
