# Custom values for airflow

# Harbor Registry credentials
registry:
  secretName: regcred

images:
    airflow:
      repository: d0-registry.acmeorg.io/airflow/airflow-custom_spark-qdrant
      tag: latest
    gitSync:
      repository: registry.k8s.io/git-sync/git-sync
      tag: v4.3.0
      pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: ssh://git@github.com:deomorxsy/pybana.git
    branch: main
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    subPath: "./dags/"
    sshKeySecret: airflow-ssh-git-secret
    # Github fingerprinting for known_hosts,
    # it is public so no need to be a secret.
    knownHosts: |
      github.com ssh-rsa RSA_DAGS_GITSYNC_KNOWNHOSTS_VALUE

webserverSecretKey: "${{ secrets.AFW_WEBSERVER_SK }}"

webserver:
  defaultUser:
    enabled: true
    username: "REP_WEBSERVER_USERNAME"
    email: airflowadmin@example.com
    firstName: Air
    lastName: Flow
    password: "REP_WEBSERVER_PASSWORD"

logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 6Gi
    # Annotations for the logs PVC
    annotations: {}
    # If using a custom storageClass, pass name here
    storageClassName: openebs-hostpath-node2
    ## the name of an existing PVC to use
    existingClaim: airflow-logs

  # persistence:
  #   enabled: true
  #   existingClaim: dags-volume
  #   accessMode: ReadWriteOnce
  #   storageClassName: openebs-hostpath-node2

#
# Default airflow repository -- overridden by all the specific images below
#- image: localhost:5000/airflow-custom-spark:1.0.0

#defaultAirflowRepository: apache/airflow


