apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-job
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  pythonFile: "gs://your-bucket/path/to/your-pyspark-script.py"
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "1g"
  sparkConf:
    "spark.executor.instances": "2"
    "spark.kubernetes.container.image": "gcr.io/spark-operator/spark:v3.1.1"
    spark.ui.port: "4045"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "hdfs://hdfs-namenode-1:8020/spark/spark-events"
  restartPolicy:
    type: Never
