---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-password
    namespace: keycloak
stringData:
    password: "\${{ secrets.RANDOM_KAP }}"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
stringData:
    username: bn_keycloak
    password: "\${{ secrets.RANDOM_KDBC }}"
    postgres-password: "\${{ secrets.RANDOM_KDBC_PSQL }}"
type: Opaque

