name: airflow

# This rule triggers when the workflow will run
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build docker image
        run: |
          docker run -d -p 5000:5000 --name registry registry:2.8.3
          docker compose -f ./compose.yml --progress=plain build airflow
          docker push localhost:5000/airflow:latest
          docker stop registry && echo "OKOK!!"


      - name: Retrieve artifact from docker image
        run: |
          docker run -it --name airflow -d --entrypoint="/bin/sh" localhost:5000/airflow:latest -c 'mkdir -p /extract; tar -czf /extract/results.tar.gz /tests/*'
          mkdir -pv ${{ github.workspace }}/artifacts/
          docker cp airflow:/extract/results.tar.gz ${{ github.workspace }}/artifacts/
          echo done!!


